packages <- c("tidyverse", 
             "ggsci", 
             "readABF", 
             "pracma", 
             "ggthemes", 
             "psych", 
             "gridExtra",
             "cowplot", 
             "readxl",
             "gridGraphics",
             "scales", 
             "reshape2",
             "tools",
             "gtools",
             "plyr", 
             "data.table",
             "viridis",
             "broom",
             "janitor",
             "plotly",
             "utils",
             "ggstatsplot")

install.packages(setdiff(packages, rownames(installed.packages())))
lapply(packages, require, character.only = TRUE)
